### ISSUE TITLE
Error when getting key which was not set before

### ISSUE THREAD

**Issue by FineFindus** [AttalliAyoub/flutter_windows_vault#1]
When trying to get a value which was not before  set a platform exception occurs.

Example code:
```dart

Future<void> main() async {
  await FlutterWindowsVault.get(key: "key");
}
```
A possible solution could be the ability to test if a keys exist, similar to [flutter_secure_storage´s](https://pub.dev/packages/flutter_secure_storage)
```dart
final storage = new FlutterSecureStorage();
await  storage.containsKey(key: "key");
```

**Comment by AttalliAyoub** [comment]
@FineFindus thank you for reporting the issue, sorry for my late response and I will make the required changes as you reported.
my regards.
